name: Run examples
on: push
jobs:
        test:
                runs-on: ubuntu-latest
                strategy:
                  matrix:
                    ocaml-version:
                      - 4.10.0
                      - 4.09.1
                      - 4.09.0
                      - 4.08.1
                      - 4.08.0
                      - 4.07.1
                      - 4.06.1
                      - 4.06.0
                      - 4.05.0
                      - 4.04.2
                      - 4.04.1
                      - 4.04.0
                      - 4.03.0
                      - 4.02.3
                      - 4.02.2
                      - 4.02.1
                steps:
                - name: Set up OCaml
                  uses: avsm/setup-ocaml@v1.0.1

                - name: install dependencies
                  run: |
                        opam install zarith
                - uses: actions/checkout@v1
                - name: run examples
                  run: |
                        git clone https://github.com/gburel/Dedukti/
                        cd Dedukti
                        git checkout polarization
                        opam install ocamlbuild menhir
                        eval $(opam env)
                        make
                        make install
                        cd ..
                        eval $(opam env)
                        ./configure
                        make
                        ./examples/launch.sh -d