name: Run examples
on: push
jobs:
        test:
                runs-on: ubuntu-latest
                strategy:
                  matrix:
                    ocaml-version:
                      - 4.10.0
                      - 4.09.1
                      - 4.09.0
                      - 4.08.1
                      - 4.07.1
                      - 4.06.1
                      - 4.06.0
                      - 4.05.0
                steps:
                - name: Set up OCaml
                  uses: avsm/setup-ocaml@v1.0.1

                - name: install dependencies
                  run: |
                        opam install zarith
                - uses: actions/checkout@v1
                - name: build zenon
                  run: |
                        eval $(opam env)
                        ./configure
                        make
                - name: run examples
                  run: |
                        ./examples/launch.sh

