name: Run examples
on: push
jobs:
        test:
                runs-on: ubuntu-latest
                strategy:
                  matrix:
                    ocaml:
                      - 4.11.1
                      - 4.11.0
                      - 4.10.2
                      - 4.10.1
                      - 4.10.0
                      - 4.09.1
                      - 4.09.0
                      - 4.08.1
                      - 4.08.0
                steps:
                - name: Set up OCaml
                  run: |
                        sudo add-apt-repository ppa:avsm/ppa
                        sudo apt update  
                        sudo apt install ocaml opam
                        opam init -a
                        opam switch create ${{matrix.ocaml}} -j 2
                        eval $(opam env)
                - name: install dependencies
                  run: |
                        opam install zarith -y -j 2
                - uses: actions/checkout@v1
                - name: run examples
                  run: |
                        git clone https://github.com/baloone/Dedukti
                        cd Dedukti
                        opam install ocamlbuild menhir -y -j 2
                        eval $(opam env)
                        make
                        make install
                        cd ..
                        eval $(opam env)
                        ./configure
                        make
                        ./examples/launch.sh -d
